# Generated by Django 6.0.4 on 2026-05-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='kompaniya ati', max_length=120, verbose_name='company')),
                ('slogan', models.CharField(blank=True, max_length=200, verbose_name='Slogan')),
                ('description', models.TextField(verbose_name='Kompaniya haqinda')),
                ('logo', models.ImageField(upload_to='about/', verbose_name='Logo')),
                ('founded_year', models.IntegerField(verbose_name="jaratilg'an jil")),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('address', models.CharField(max_length=255, verbose_name="Ma'nzil")),
            ],
        ),
        migrations.CreateModel(
            name='cm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('subject', models.CharField()),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='home')),
                ('description', models.TextField(verbose_name='description')),
                ('button_text', models.CharField(max_length=50, verbose_name='Button')),
                ('demo_link', models.URLField(blank=True, verbose_name='link')),
                ('hero_image', models.ImageField(upload_to='home/', verbose_name='img')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="product jazin'", max_length=120, verbose_name='title')),
                ('text', models.TextField(help_text="komment qaldirin'", verbose_name='desciption')),
                ('img', models.ImageField(upload_to='products/', verbose_name='image or picture')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='services/')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
